### ISSUE TITLE
ADDR already in use ? 

### ISSUE THREAD

**Issue by sebs** [LearnBoost/tobi#19]
When I reduce the standard example to a bare minimum, the Error message is: ERR ADDR already in use. Can you maybe deliver a bare minimum tobi test as expresso does for the unit tests? This would be a really easy entrance to tobi.

**Comment by sebs** [comment]
node.js:63
    throw e;
    ^
Error: EADDRINUSE, Address already in use
    at net:1256:18
    at Object.lookup (dns:136:5)
    at Server.<anonymous> (net:1250:9)
    at Server.<anonymous> (/usr/local/lib/node/.npm/connect/0.5.0/package/lib/connect/index.js:149:34)
    at Server.listen (/usr/local/lib/node/.npm/express/1.0.0/package/lib/express/server.js:94:35)
    at Browser.request (/usr/local/lib/node/.npm/tobi/0.0.8/package/lib/browser.js:128:14)
    at Browser.<anonymous> (/usr/local/lib/node/.npm/tobi/0.0.8/package/lib/browser.js:241:15)
    at Object.<anonymous> (/home/sebs/nodeprojects/tpdbmobile/tobi/test.js:5:9)
    at Module._compile (node.js:462:23)
