### ISSUE TITLE
broken jquery path in npm

### ISSUE THREAD

**Issue by afiore** [LearnBoost/tobi#20]
I've just installed Tobi, and I am trying to run the following snippet with node v0.3.2-pre

```
var tobi = require('tobi')
     , browser = tobi.createBrowser(80, 'site.local');

browser.get('/index.php/example',function(res,$){
    console.info(res);
});
```

Output:

```
node.js:59
throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module '../support/jquery'
at resolveModuleFilename (node.js:255:13)
at loadModule (node.js:217:20)
at require (node.js:281:14)
at Object.<anonymous> (/usr/local/lib/node/.npm/tobi/0.1.0/package/lib/browser.js:16:14)
at Module._compile (node.js:336:30)
at Object..js (node.js:344:12)
at Module.load (node.js:269:25)
at loadModule (node.js:241:12)
at require (node.js:281:14)
at Object.<anonymous> (/usr/local/lib/node/.npm/tobi/0.1.0/package/lib/tobi.js:18:19)
```

Thanks, 
A

**Comment by tj** [comment]
Fixed jquery npm issue. Closed by 1608fb892f42763319797d8fea019ac3e4e1096c
