### ISSUE TITLE
Tobi breaks

### ISSUE THREAD

**Issue by samyakbhuta** [LearnBoost/tobi#35]
I am getting an error which is as follow.

```
/home/Api/tests/scripts/vows/node_modules/tobi/lib/browser.js:192
      if (~contentType.indexOf('json')) {
                       ^
TypeError: Cannot call method 'indexOf' of undefined
    at ClientRequest.<anonymous> (/home/Api/tests/scripts/vows/node_modules/tobi/lib/browser.js:192:24)
    at ClientRequest.emit (events.js:64:17)
    at HTTPParser.onIncoming (http.js:1593:9)
    at HTTPParser.onHeadersComplete (http.js:108:31)
    at Client.onData [as ondata] (http.js:1471:27)
    at Client._onReadable (net.js:681:27)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```

This is the case when I am trying to test a POST method ( `browser.post('/v0.5/posttest', data, this.callback);` with vows.js as framework.) and the post does nothing but `res.end()` using express.js.

**Comment by tj** [comment]
hmm that's interesting because I have `if (!contentType) return fn(res);` in there already, so `undefined` would clearly take that path, something funky is going on

**Comment by cmeiklejohn** [comment]
I'm running into a possibly similar issue where if I perform two browser.get requests sequential batches with vows, the second one returns undefined for everything, and never makes a request directly to the app.
