### ISSUE TITLE
test for 'test select multiple options' in browser.navigation.js fails

### ISSUE THREAD

**Issue by bantic** [LearnBoost/tobi#39]
I get the following stacktrace.  Only one forum digest option comes back as selected, when it should be both.  This happens when I run `make test` on a newly-checked-out clone of the repo.

This is the test that is failing: https://github.com/LearnBoost/tobi/blob/master/test/browser.navigation.test.js#L700

```
   uncaught: AssertionError: expected { user: 
   { name: '',
     subscribe: 'yes',
     forum_digest: 'weekly',
     signature: '' } } to equal { user: 
   { name: '',
     signature: '',
     subscribe: 'yes',
     forum_digest: [ 'daily', 'weekly' ] } }
    at Object.eql (/Users/bantic/tobi/node_modules/should/lib/should.js:291:10)
    at /Users/bantic/tobi/test/browser.navigation.test.js:720:30
    at IncomingMessage.<anonymous> (/Users/bantic/tobi/lib/browser.js:201:24)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Client.onData [as ondata] (http.js:1484:27)
    at Client._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback] (net.js:177:10)


   uncaught: Error: 'test select multiple options' timed out
    at Object._onTimeout (/Users/bantic/tobi/node_modules/expresso/bin/expresso:835:43)
    at Timer.callback (timers.js:83:39)
```

**Comment by tj** [comment]
weird i get that now too, something must have changed

**Comment by mhemesath** [comment]
This should be resolved now, can we close this?

**Comment by bantic** [comment]
Yeah...they pass for me now, too. Thanks.
