### ISSUE TITLE
has no method 'find' when Browser.click invoked.

### ISSUE THREAD

**Issue by renzhichao** [LearnBoost/tobi#49]
When I try to run some examples code with nodejs 0.5.0pre with tobi 0.3.0 and found the below error stack trace. 

Could you help me about it ?

:/opt/node/lib/node_modules/tobi/examples# node google.js 

/opt/node/lib/node_modules/tobi/lib/browser.js:425
  var elems = this.context.find(selector).filter(function(){  
                           ^
TypeError: Object function (selector, fn){
  var prev = this.context;
  this.context = this.context.find(selector);
  fn();
  this.context = prev;
  return this;
} has no method 'find'
    at Browser.locate (/opt/node/lib/node_modules/tobi/lib/browser.js:425:28)
    at Browser.click (/opt/node/lib/node_modules/tobi/lib/browser.js:458:27)
    at /opt/node/lib/node_modules/tobi/examples/google.js:12:11
    at IncomingMessage.<anonymous> (/opt/node/lib/node_modules/tobi/lib/browser.js:264:9)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.onend (http.js:1264:12)
    at Socket._onReadable (net_legacy.js:659:26)
    at IOWatcher.onReadable [as callback](net_legacy.js:177:10)

**Comment by tj** [comment]
dont use 0.5.x yet... it's unstable for a reason, stuff like this will break
