### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by pvencill** [LearnBoost/tobi#61]
Tried following the example on the docs and get "connection refused".  The app works fine when I fire it up in node and navigate through curl or a browser.

**Comment by craftgear** [comment]
Don't you write like this?

```
browser = tobi.createBrowser("3000", "localhost");
```

This makes "Error: ECONNREFUSED, Connection refused" error.

Make sure the first argument is a number not a string.

```
browser = tobi.createBrowser(3000, "localhost");
```

**Comment by yevgenko** [comment]
thank @craftgear `browser = tobi.createBrowser(3000, "localhost");` works for me, probably typo in readme?? i.e.:`browser = tobi.createBrowser(app);` doesn't work  "Error: ECONNREFUSED, Connection refused"

**Comment by craftgear** [comment]
no worries :-)

**Comment by nagyv** [comment]
I have the same error:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:642:11)
    at Object.afterConnect [as oncomplete] (net.js:633:18)
```

I've tried both `browser = tobi.createBrowser(3000, 'localhost');` and `browser = tobi.createBrowser(app);`, the same error occured

my code is simply a vow topic

```
      browser.post(
        '/register', 
        {
          login: 'mylogin', 
          password: 'password',
          password2: 'password'
        }, 
        this.callback
      );
```

I'm running tobi 0.3.2, express 2.5.8, node 0.6.10

any ideas how to avoid this error? even a working version triad is fine :)

**Comment by richzw** [comment]
+1
